#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata": {"name": "blog-frontend"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by="name"
      - name: blog-frontend
        image: ghcr.io/categolj/blog-frontend:5.0.0-snapshot-lab