version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.github.eirslett:frontend-maven-plugin
    versions:
    - 1.11.0
- package-ecosystem: npm
  directory: "/blog-frontend-ui"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: recharts
    versions:
    - 2.0.4
    - 2.0.6
    - 2.0.7
  - dependency-name: marked
    versions:
    - 1.2.8
    - 1.2.9
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
