apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blog-frontend
  namespace: blog
spec:
  endpoints:
  - interval: 30s
    port: http
    path: /actuator/prometheus
    basicAuth:
      username:
        name: blog-config-secret
        key: ops-username
      password:
        name: blog-config-secret
        key: ops-password
  namespaceSelector:
    matchNames:
    - blog
  selector:
    matchLabels:
      app: blog-frontend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: blog
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: blog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring