kind: Service
apiVersion: v1
metadata:
  name: blog-frontend
  namespace: blog
  labels:
    app: blog-frontend
spec:
  selector:
    app: blog-frontend
  ports:
    - protocol: TCP
      port: 8080
      name: http
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-frontend
  namespace: blog
  labels:
    app: blog-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-frontend
  template:
    metadata:
      labels:
        app: blog-frontend
    spec:
      containers:
      - name: blog-frontend
        image: making/blog-frontend:5.0.0-SNAPSHOT
        ports:
          - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: PROMETHEUS_URL
          value: https://prometheus-generous-bear-lx.apps.pcfone.io/
        - name: JAVA_OPTS
          value: " -XX:ReservedCodeCacheSize=32M -Xss512k -Duser.timezone=Asia/Tokyo -Duser.language=ja -Duser.country=JP"
        - name: BPL_JVM_THREAD_COUNT
          value: "20"
        - name: SPRING_ZIPKIN_SERVICE_NAME
          value: "${INFO_K8S_NAMESPACE}:frontend"
        - name: SPRING_ZIPKIN_BASE_URL
          value: https://zipkin.dev.ik.am
        - name: LOGGING_EXCEPTION_CONVERSION_WORD
          value: "\t%replace(%replace(%xEx){'\n','@n@'}){'\t','    '}%nopex"
        - name: LOGGING_PATTERN_CONSOLE
          value: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${logging.pattern.level:%5p}) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %replace(%m){'\n','@n@'}${logging.exception-conversion-word:%wEx}%n"
        - name: SPRING_SLEUTH_SAMPLER_RATE
          value: "30"
        - name: PRERENDER_URL
          value: https://service.prerender.io
        - name: PRERENDER_TOKEN
          valueFrom:
            secretKeyRef:
              name: blog-frontend
              key: predender-token
        - name: INFO_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INFO_K8S_POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INFO_K8S_APP
          value: "${spring.application.name}"
        - name: INFO_JAVA_VERSION
          value: "${java.runtime.version}"
        - name: INFO_JAVA_VENDOR
          value: "${java.vm.vendor}"          
        - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_RSOCKET_HOST
          value: prometheus-proxy.dev.bosh.tokyo
        - name: MANAGEMENT_METRICS_TAGS_ORGANIZATION
          value: cfcr-aws
        - name: MANAGEMENT_METRICS_TAGS_SPACE
          value: "${INFO_K8S_NAMESPACE}"
        - name: MANAGEMENT_METRICS_TAGS_APPLICATION
          value: "${INFO_K8S_APP}"
        - name: MANAGEMENT_METRICS_TAGS_INSTANCE_ID
          value: "${INFO_K8S_POD}"
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "200Mi"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
      affinity:
         podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             - labelSelector:
                 matchExpressions:
                   - key: "app"
                     operator: In
                     values:
                     - blog-frontend
               topologyKey: "kubernetes.io/hostname"
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: blog-frontend
  namespace: blog
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: blog-frontend
