apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: blog-frontend
  namespace: blog
spec:
  virtualhost:
    fqdn: blog.lab.maki.lol
    tls:
      secretName: certificate-tls
  routes:
  - conditions:
    - prefix: /rsocket
    enableWebsockets: true
    services:
    - name: blog-rsocket
      port: 8080
  - services:
    - name: blog-frontend
      port: 8080