@startuml
(Crawler)
actor User

node "frontend" {
  [ui]
  [server]
}

node "api"  {
}

database "db" {
}

cloud "Prerender" {
}


[server] --> Prerender
[ui] --> api
api -> db

Prerender -> ui

User -> ui
Crawler -> [server]
@enduml
