name: Frontend UI Only
on:
  push:
    branches:
    - master
    paths:
    - blog-frontend-ui/**
    - .github/workflows/dependabot.yml
    - .github/workflows/blog-frontend-ui-only.yml
  pull_request:
    branches:
    - master
    paths:
    - blog-frontend-ui/**
    - .github/workflows/dependabot.yml
    - .github/workflows/blog-frontend-ui-only.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: buildpacks/github-actions/setup-pack@v4.8.0
    - name: build-image
      if: github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      run: |
        set -e
        mkdir -p ~/.docker
        cat <<EOF > ~/.docker/config.json
        {"auths":{"${DOCKER_REGISTRY}":{"username":"${DOCKER_USERNAME}","password":"${DOCKER_PASSWORD}"}}}
        EOF
        IMAGE_NAME=ghcr.io/categolj/blog-frontend-ui
        pack build ${IMAGE_NAME} --builder paketobuildpacks/builder:base -p blog-frontend-ui -e BP_NODE_RUN_SCRIPTS=build -e BP_WEB_SERVER=nginx -e BP_WEB_SERVER_ROOT=build -e BP_WEB_SERVER_ENABLE_PUSH_STATE=true -e REACT_APP_BLOG_API=auto -e REACT_APP_BLOG_UI=auto --publish
