name: CI
on:
  push:
    branches:
    - master
    paths:
    - blog-frontend-server/**
    - blog-frontend-ui/**
    - pom.xml
    - .github/workflows/ci.yml
  pull_request:
    branches:
    - master
    paths:
    - blog-frontend-server/**
    - blog-frontend-ui/**
    - pom.xml
    - .github/workflows/ci.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.x'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: mvn test
      run: |
        set -e    
        ./mvnw -V test
    - name: mvn deploy
      if: github.ref == 'refs/heads/master'
      env:
        REACT_APP_BLOG_API: https://blog-api.ik.am
        REACT_APP_BLOG_UI: https://blog.ik.am
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        set -e
        BOOT_VERSION=$(grep '<version>' pom.xml | head -n 1 | sed -e 's|<version>||g' -e 's|</version>||g' -e 's|<.*>||g' -e 's| ||g')
        cat > settings.xml <<EOF
        <settings>
          <servers>
            <server>
               <id>github</id>
               <username>${DOCKER_USERNAME}</username>
               <password>${DOCKER_PASSWORD}</password>
            </server>
          </servers>
        </settings>
        EOF
        sed -i 's|</project>|<distributionManagement><repository><id>github</id><name>github</name><url>https://maven.pkg.github.com/categolj/blog-frontend</url></repository></distributionManagement></project>|' pom.xml
        ./mvnw -V deploy -s settings.xml -DskipTests=true -DserverId=github -Dspring-boot.version=${BOOT_VERSION}
    - name: pack build
      if: github.ref == 'refs/heads/master'
      env:
        PACK_VERSION: 0.18.0
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      run: |
        set -e
        docker login ${DOCKER_REGISTRY} -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        VERSION=$(grep '<version>' pom.xml | head -n 2 | tail -n 1 | sed -e 's|<version>||g' -e 's|</version>||g' -e 's| ||g')
        IMAGE_NAME=${DOCKER_REGISTRY}:${VERSION}
        wget -q https://github.com/buildpacks/pack/releases/download/v${PACK_VERSION}/pack-v${PACK_VERSION}-linux.tgz
        tar xzf pack-*.tgz
        rm -f pack-*.tgz
        set +e
        docker pull ${IMAGE_NAME}
        set -e
        ./pack build ${IMAGE_NAME} \
          -p blog-frontend-server/target/blog-frontend-server-*.jar  \
          --builder gcr.io/paketo-buildpacks/builder:base
        docker push ${IMAGE_NAME}
        docker pull ${IMAGE_NAME}
        cat <<EOF > values-prod.yml
        #@data/values
        #@overlay/match-child-defaults missing_ok=True
        ---
        git_repo: https://github.com/categolj/blog-frontend
        git_commit: $(git rev-parse HEAD)
        image_digest: $(docker inspect --format='{{index .RepoDigests 0}}' ${IMAGE_NAME} | awk -F '@' '{print $2}')
        EOF
        cat values-prod.yml
    - name: mvn package lab
      if: github.ref == 'refs/heads/master'
      env:
        REACT_APP_BLOG_API: https://blog-api.lab.maki.lol
        REACT_APP_BLOG_UI: https://blog.lab.maki.lol
      run: |
        set -e
        BOOT_VERSION=$(grep '<version>' pom.xml | head -n 1 | sed -e 's|<version>||g' -e 's|</version>||g' -e 's|<.*>||g' -e 's| ||g')
        ./mvnw -V package -DskipTests -Dspring-boot.version=${BOOT_VERSION}
    - name: pack build lab
      if: github.ref == 'refs/heads/master'
      env:
        PACK_VERSION: 0.17.0
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      run: |
        set -e
        docker login ${DOCKER_REGISTRY} -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        VERSION=$(grep '<version>' pom.xml | head -n 2 | tail -n 1 | sed -e 's|<version>||g' -e 's|</version>||g' -e 's| ||g')
        IMAGE_NAME=${DOCKER_REGISTRY}:${VERSION}-lab
        wget -q https://github.com/buildpacks/pack/releases/download/v${PACK_VERSION}/pack-v${PACK_VERSION}-linux.tgz
        tar xzf pack-*.tgz
        rm -f pack-*.tgz
        set +e
        docker pull ${IMAGE_NAME}
        set -e
        ./pack build ${IMAGE_NAME} \
          -p blog-frontend-server/target/blog-frontend-server-*.jar  \
          --builder gcr.io/paketo-buildpacks/builder:base
        docker push ${IMAGE_NAME}
        docker pull ${IMAGE_NAME}
        cat <<EOF > values-dev.yml
        #@data/values
        #@overlay/match-child-defaults missing_ok=True
        ---
        git_repo: https://github.com/categolj/blog-frontend
        git_commit: $(git rev-parse HEAD)
        image_digest: $(docker inspect --format='{{index .RepoDigests 0}}' ${IMAGE_NAME} | awk -F '@' '{print $2}')
        EOF
        cat values-dev.yml
    - name: update config
      if: github.ref == 'refs/heads/master'
      env:
        REPOSITORY: making/config
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GIT_NAME: ${{ secrets.GIT_NAME }}
        GIT_SSH_KEY: ${{ secrets.GIT_SSH_KEY }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE: master
        APP_NAME: blog-frontend
      run: |
        set -ex
        GIT_REV=$(git rev-parse HEAD)
        COMMIT_MESSAGE="[Dev] Bump to categolj/${APP_NAME}@${GIT_REV}"
        mkdir -p ~/.ssh
        cat > ~/.ssh/config <<EOF
        StrictHostKeyChecking no
        LogLevel quiet
        EOF
        cat > ~/.ssh/id_rsa <<EOF
        ${GIT_SSH_KEY}
        EOF
        chmod 0600 ~/.ssh/*

        git config --global user.email "${GIT_EMAIL}"
        git config --global user.name "${GIT_NAME}"
        git clone git@github.com:${REPOSITORY}.git
        cd $(echo ${REPOSITORY} | awk -F '/' '{print $2}')

        # Update dev directly
        cp ../values-dev.yml home-lab/grape/app/${APP_NAME}/dev/values.yml
        git diff
        git add -A
        git commit -m "${COMMIT_MESSAGE}"
        git push origin ${BASE}
        DEV_REV=$(git rev-parse HEAD)

        # send a pull request to prod
        BRANCH_NAME="update-${APP_NAME}-prod-${GIT_REV}"
        COMMIT_MESSAGE="[Prod] Bump to categolj/${APP_NAME}@${GIT_REV}"
        git checkout -b ${BRANCH_NAME}
        cp ../values-prod.yml home-lab/grape/app/${APP_NAME}/prod/values.yml
        git diff
        git add -A
        git commit -m "${COMMIT_MESSAGE}"
        git push origin ${BRANCH_NAME}
        curl -u ${GIT_NAME}:${ACCESS_TOKEN} -H "Content-Type: application/json" -X POST -d "{\"title\":\"${COMMIT_MESSAGE}\",\"body\":\"See https://github.com/categolj/${APP_NAME}/commit/${GIT_REV}\nCorresponding commit to dev env is ${DEV_REV}\",\"head\":\"${BRANCH_NAME}\",\"base\":\"${BASE}\"}" https://api.github.com/repos/${REPOSITORY}/pulls
